"
In GS64, ArgumentError identifies a situation in which an argument to a method is invalid.
The type of the argument may be valid (else it would be an ArgumentTypeError)
but there is something else incorrect about an argument.

This version is just a placeholder so we can easily create extensions methods to load in GS64 specific
packages.
"
Class {
	#name : 'ArgumentError',
	#superclass : 'ImproperOperation',
	#category : 'Buoy-GS64-Compatibility',
	#package : 'Buoy-GS64-Compatibility'
}
