"
In GS64, a `ClassOrganizer` can answer queries about classes in the image, provides tools and reports
on information on classes and methods and can perform cross-referencing and fileout.

This version is just a placeholder so we can easily create extension methods referencing this class
in GS64 specific packages.
"
Class {
	#name : #ClassOrganizer,
	#superclass : #Object,
	#category : #'Buoy-GS64-Compatibility'
}
