"
In GS64, this protocol describes the behavior that is common to date
time objects. Date time objects represent individual points
in Coordinated Universal Time (UTC) as represented in an
implementation defined local time, with a default resolution
of seconds.

This version is just a placeholder so we can easily create extensions methods to load in GS64 specific
packages.
"
Class {
	#name : #DateAndTimeANSI,
	#superclass : #Magnitude,
	#category : #'Buoy-GS64-Compatibility'
}
