"
In GS64, creating an index involves creating an instance of GsIndexSpec and sending messages to
define the index and the parameters and options for that index, then use this spec to create
indexes on a specific collection.

This version is just a placeholder so we can easily create extensions methods to load in GS64 specific
packages.
"
Class {
	#name : 'GsIndexSpec',
	#superclass : 'Object',
	#category : 'Buoy-GS64-Compatibility',
	#package : 'Buoy-GS64-Compatibility'
}
