name: 'GS64 Components Loading'
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
   component-loading:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gs64-ci:
          - ba-st-actions/gs64-ci@v2 #GS64 3.7.0
          - ba-st-actions/gs64-ci@v3 #GS64 3.7.1
        load-spec:
          - Dependent-SUnit-Extensions
          - Deployment
    name: GS64 + ${{ matrix.load-spec }}
    steps:
      - uses: actions/checkout@v4
      - name: Load component in image
        uses: ${{ matrix.gs64-ci }}
        with:
          project_name: 'Buoy'
          load_spec: 'Buoy-${{ matrix.load-spec }}'
