name: Baseline groups
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  group-loading:
    name: Group ${{ matrix.load-spec }}
    strategy:
      fail-fast: false
      matrix:
        load-spec:
          - development
          - dependent-sunit-extensions
          - deployment
          - tests
          - tools
    uses: ./.github/workflows/loading-pharo-group.yml
    with:
      load-spec: ${{ matrix.load-spec }}
