name: Pharo Unit Tests
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
   unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pharo-version:
          - 10
          - 11
          - 12
          - 13
    name: Pharo64-${{ matrix.pharo-version }}
    steps:
      - uses: actions/checkout@v6
      - name: Load Image and Run Tests
        uses: ba-st-actions/pharo-ci@${{ matrix.pharo-version }}
        with:
          spec: .smalltalkci/.unit-tests.ston
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 15
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          name: Unit-Tests-${{matrix.smalltalk}}
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unit
